language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
bundler_args: --without development production
before_script:
  - cp config/database.yml.example config/database.yml
  - mysql -e 'CREATE DATABASE sparkler_test;'
