# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a0fb7cab80fe9e68686e0ec416427089fee1f037b3606508518ec90f2d7cb2c3ce59542d95b1a4f2534849400613acab2f4d6f12a79c85dcaeb20ced4b8a23d

test:
  secret_key_base: 2add29d1e241f0d3da91652e620804366926b3f7985dacf8a753bdabbfbd6fea8e0a9287aa5d943aa20cd025d42646d781488b65b3284641eaa6bf567a9481b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
